USE [master]
GO

/****** Object:  Database [StoryTeller]    Script Date: 04/12/2023 14:25:39 ******/
CREATE DATABASE [StoryTeller]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StoryTeller', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StoryTeller.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StoryTeller_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StoryTeller_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StoryTeller].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StoryTeller] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StoryTeller] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StoryTeller] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StoryTeller] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StoryTeller] SET ARITHABORT OFF 
GO

ALTER DATABASE [StoryTeller] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StoryTeller] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StoryTeller] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StoryTeller] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StoryTeller] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StoryTeller] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StoryTeller] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StoryTeller] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StoryTeller] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StoryTeller] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StoryTeller] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StoryTeller] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StoryTeller] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StoryTeller] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StoryTeller] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StoryTeller] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [StoryTeller] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StoryTeller] SET RECOVERY FULL 
GO

ALTER DATABASE [StoryTeller] SET  MULTI_USER 
GO

ALTER DATABASE [StoryTeller] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StoryTeller] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StoryTeller] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StoryTeller] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StoryTeller] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StoryTeller] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StoryTeller] SET  READ_WRITE 
GO

